# Generated by Django 4.1.4 on 2023-01-01 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('png', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'sp',
            },
        ),
        migrations.CreateModel(
            name='ssp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=100)),
                ('spng', models.CharField(max_length=200)),
                ('spic', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'ssp',
            },
        ),
    ]
